version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gutz
      POSTGRES_PASSWORD: gutz
      POSTGRES_DB: taskflow
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
